version: '3'
services:
  postgres:
    image: postgres:16
    container_name: postgres-16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    restart: always
  backend:
    build: ./project
    container_name: backend
    command: npm run start
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"